### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by p1g3** [wyzxxz/shiro_rce#3]
命令：java -cp shiro_tool.jar Shiro http://xxx/ key=kPH+bIxk5D2deZiIxcaaaA==

`Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/syndication/feed/impl/ObjectBean
        at ysoserial.payloads.ROME.getObject(ROME.java:37)
        at ysoserial.payloads.util.PayloadRunner$1.call(PayloadRunner.java:29)
        at ysoserial.payloads.util.PayloadRunner$1.call(PayloadRunner.java:22)
        at ysoserial.secmgr.ExecCheckingSecurityManager.callWrapped(ExecCheckingSecurityManager.java:72)
        at ysoserial.payloads.util.PayloadRunner.run(PayloadRunner.java:22)
        at Shiro.getBaseData(Shiro.java:353)
        at Shiro.main(Shiro.java:145)
Caused by: java.lang.ClassNotFoundException: com.sun.syndication.feed.impl.ObjectBean
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 more
`

**Comment by wyzxxz** [comment]
好了
